Firefox OS on a High End Device
===============================

:hp-tags: Firefox OS, B2G, Sony Xperia Z3 Compact

It all started with one tweet!! 

+++<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">My Phone Runs on JavaScript - great Firefox OS intro deck from <a href="https://twitter.com/jedireza">@jedireza</a> <a href="http://t.co/JksO42aP2B">http://t.co/JksO42aP2B</a></p>&mdash; dietrich ayala (@dietrich) <a href="https://twitter.com/dietrich/status/628270494190542849">August 3, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>+++

Here you can clearly see from the slides that Firefos OS runs on Sony Xperia Z3 Compact. And so the experiment began!!


Unlocking the bootloader
^^^^^^^^^^^^^^^^^^^^^^^^
For someone who has never created android mods, or played with android, it was really difficult to understand the steps that had to be followed in order to install Firefox OS. And so the first step _Unlocking The Bootloader_ turned out to be more challenging than I had originally thought. But in the end, the bootloader was unlocked, and I got to play with some of the bootloader options.


Building for aries-l
^^^^^^^^^^^^^^^^^^^^

Now that the bootloader was unlocked, I decided to install firefox os on this device which had Android 5.1.1 or you can say the most updated version of Android. 

____
aries-l is the code name for Sony Xperia Z3 Compact device running Android 5.
____

After following the MDN docs on firefox OS for aries-l build, I started the build process on my mac. But after downloading the files, the build process failed. After talking to the community, I found out that the build process for Android 5.0+ was broken. Not only that, the build process doesnt work on Mac at all. 

Flashing the phone with 4.4
^^^^^^^^^^^^^^^^^^^^^^^^^^^

After realizing that the previous step was a total failure and talking to the people in community, I decided to flash the devices with Android 4.4.


Building for aries
^^^^^^^^^^^^^^^^^^

This time instead of using a Mac to build Firefox OS, I used a linux machine. ___(incase you are wondering why I did not use a virtual machine, well I did, but the process kept on failing after pulling the files from the device)___

____
aries is the code name for Sony Xperia Z3 Compact device running Android 4.4.
____

And this time, it was a success. I was finally able to see the device running Firefox OS.

*Some of the settings from the device are as follows*

[cols="2*"]
|===
| *Setting Name*
| *Value*

| Model
| Xperia Z3 Compact(B2G)

| Software
| Boot2Gecko 2.5.0.0-prerelease

|===

Outcome
^^^^^^^

The final outcome is a High End Device runnning Firefox OS.

video::EyGAyjMobb8[youtube]

There are definitely a lot of things that can be done to improve the OS even more. But right now, it is smoother than the one running on GeeksPhone Revolution or Peak.
